# cloud-config
apt:
  sources:
    hashicorp:
      source: "deb https://apt.releases.hashicorp.com $RELEASE main"
      keyid: 798AEC654E5C15428C8E42EEAA16FCBCA621E701

    docker:
      source: "deb https://download.docker.com/linux/ubuntu $RELEASE stable"
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - jq
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  - vault
  - python3.10-venv

# Used in Vegeta HTTP Load Testing
write_files:
  owner: ubuntu:ubuntu
  path: /home/ubuntu/targets.txt
  content: |
    GET https://127.0.0.1:8000/db/users
    Accept: application/json

runcmd:
  - usermod -aG docker ubuntu
  - sudo snap install go --classic
  - go install github.com/tsenart/vegeta@latest

  - echo "export GOPATH=$HOME/go" >> /home/ubuntu/.bashrc
  - echo "export PATH=$PATH:$GOROOT/bin:$GOPATH/bin" >> /home/ubuntu/.bashrc

  - export POSTGRES_PASSWORD=$(uuidgen)
  - export VAULT_ADDR=http://localhost:8200
  - export VAULT_TOKEN=root

  - git clone https://github.com/michaelkosir/vault-python-webapp.git /tmp/vault-python-webapp

  - ./tmp/vault-python-webapp/demo/scripts/setup-vm.sh
  - ./tmp/vault-python-webapp/demo/scripts/setup-postgres.sh
  - ./tmp/vault-python-webapp/demo/scripts/setup-vault.sh

  - systemctl enable vault-agent vault-proxy gunicorn
  - systemctl start vault-agent vault-proxy
  - systemctl start gunicorn
